In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import math
from cmdstanpy import CmdStanModel

/opt/miniconda3/envs/genetics_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# Prepare for the data
# true_N is all 5000
# true_T is [50,500,1000]

ibd = pd.read_json('../ibd_admix_data.json')
ibd['index'] = ibd['index'].apply(tuple)
ibd['group'] = ibd['group'].apply(tuple)
grouped = ibd.groupby(['group','u','v'])
n_boot = 1000

columns = ['group','mean_fraction','mean_number','boot_var','p_0','u','v']
boot_data = pd.DataFrame(columns = columns)
for name, group in grouped:
    gg = name[0]
    u = name[1]
    v = name[2]
    non_zero = [i for i in group['fraction'] if i > 0]
    p_0 = 1- (len(non_zero)/len(group['fraction']))
    number_mean = group['number'].mean()
    sample_mean = group['fraction'].mean()
    bootstrap_means = []

    for _ in range(n_boot):
        sample = np.random.choice(group['fraction'], size=len(group['fraction']), replace=True)
        bootstrap_means.append(np.mean(sample))

# Estimate variance
    variance_estimate = np.var(bootstrap_means)
    new_row = [gg,sample_mean,number_mean,variance_estimate,p_0,u,v]
    boot_data.loc[len(boot_data)] = new_row

In [5]:
print(boot_data.head())

    group  mean_fraction  mean_number      boot_var       p_0    u    v
0  (0, 0)       0.003260     1.793590  7.891003e-09  0.157692  0.5  0.6
1  (0, 0)       0.002450     1.138462  6.830971e-09  0.320513  0.6  0.7
2  (0, 0)       0.001654     0.664103  4.798435e-09  0.505128  0.7  0.8
3  (0, 0)       0.001580     0.558974  5.788429e-09  0.566667  0.8  0.9
4  (0, 0)       0.001173     0.370513  4.919729e-09  0.697436  0.9  1.0

In [6]:
boot_data['mean_fraction'] = boot_data['mean_fraction'] * 1000
boot_data['boot_var'] = np.sqrt(boot_data['boot_var']) * 1000
boot_data['group'] = boot_data['group'].apply(list)
json_ibd = boot_data.to_dict(orient='list')
print(json_ibd)
json_ibd['N_obs'] = len(boot_data)
json_ibd['length'] = 300
json_ibd['outgroup_N'] = 10000
json_ibd['ancestral_T'] = 1000
json_ibd['T2'] = 500
json_ibd['ancestral_N'] = 10000

{'group': [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'mean_fraction': [3.259597863247568, 2.4495396153843845, 1.6544307264955642, 1.5797405128203563, 1.1729677350426306, 3.4728456837604824, 1.8735140170939233, 3.9112305128204095, 1.0809980769230707, 2.4727808541664, 1.8497216458331238, 1.322142979166527, 0.9704910833332314, 0.7478553333332731, 2.117437770833196, 1.10816072916661, 1.128815833333295, 0.0, 0.3631329166666075, 0.10677235416665126, 0.0476511249999925, 0.023184145833330623, 0.009885479166665, 0.011504166666665627, 0.0, 0.0, 0.0, 0.002367187499999375, 0.0014458125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.134132564102309, 1.6082552136750472, 1.3288258974357576, 0.9067842307691372, 0.6356429487178962, 2.1386467521366184, 1.144785213675154, 3.373270341880258, 1.085757564102559, 1.1140267291665062, 0.6641664374999037, 0.47254158333327567, 0.3153708124999656, 0.3018633124999663, 0.6373256874999474, 0.35019924999998003, 0.2496689791666575, 0.0, 0.006979999999999375, 0.0, 0.0016252291666662504, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.164992008546704, 2.1833314957262746, 1.8936964102562208, 1.413943504273355, 1.000019059828968, 3.3887482478630733, 1.796009914529817, 3.497460170940085, 0.9007379914529859, 0.011504020833330627, 0.0028025416666662504, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.305824658119357, 2.3544655555553247, 1.6674418803417048, 1.259786837606704, 1.1848652136751037, 3.5499659829057864, 1.3941319658118874, 4.016102735042639, 1.0275129487179449], 'mean_number': [1.7935897435897437, 1.1384615384615384, 0.6641025641025641, 0.558974358974359, 0.37051282051282053, 0.8653846153846154, 0.32564102564102565, 0.3576923076923077, 0.017948717948717947, 1.35875, 0.860625, 0.531875, 0.343125, 0.23625, 0.53, 0.194375, 0.12125, 0.0, 0.2025, 0.05, 0.019375, 0.008125, 0.003125, 0.003125, 0.0, 0.0, 0.0, 0.00125, 0.000625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1717948717948719, 0.7474358974358974, 0.5333333333333333, 0.3217948717948718, 0.2012820512820513, 0.5307692307692308, 0.1987179487179487, 0.3153846153846154, 0.015384615384615385, 0.615, 0.30875, 0.19, 0.111875, 0.09625, 0.16125, 0.0625, 0.02625, 0.0, 0.00375, 0.0, 0.000625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.7423076923076923, 1.0128205128205128, 0.764102564102564, 0.5, 0.31666666666666665, 0.85, 0.3128205128205128, 0.3294871794871795, 0.01282051282051282, 0.006875, 0.00125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.8166666666666667, 1.0935897435897435, 0.6666666666666666, 0.4461538461538462, 0.37435897435897436, 0.8858974358974359, 0.24487179487179486, 0.3371794871794872, 0.014102564102564103], 'boot_var': [0.08883131860627787, 0.08264968831725485, 0.06927073439722199, 0.07608172815600438, 0.0701407818972744, 0.13214428281512117, 0.11908342633091289, 0.24611731921415528, 0.3414007673393705, 0.05334248869129609, 0.04745315724646409, 0.04491773371572289, 0.04105444637491099, 0.0374214080541657, 0.07406252984338899, 0.06134824395977367, 0.08303961506235515, 0.0, 0.02078235967838171, 0.012439208350904455, 0.008599008125922174, 0.006501577883470762, 0.004246080105711615, 0.005088337069424356, 0.0, 0.0, 0.0, 0.001735512343164842, 0.0014242353954915584, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07113756677093441, 0.06807287459554599, 0.06638376572949321, 0.06019079392454387, 0.04981616559500138, 0.1055586185264937, 0.09345023616529878, 0.23956894923274635, 0.34841714945990737, 0.03476519174152217, 0.02878103704611453, 0.027023896249171748, 0.024014604864056162, 0.024851183325577002, 0.039037122928004805, 0.03499188702204975, 0.04039028693649868, 0.0, 0.0029820498155603884, 0.0, 0.0015804307030440486, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08529333381129382, 0.07903314994159145, 0.07511600601667605, 0.07406431929303364, 0.06512983760135202, 0.13307559941515598, 0.12384984736925808, 0.23431179290915202, 0.333731001263081, 0.00344187274578859, 0.001998036319027497, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08624344282142828, 0.0754991656542846, 0.06904579706536473, 0.06806211120390417, 0.06792778468801958, 0.13018886872814472, 0.10144075318021843, 0.28457231030711627, 0.4813442681713051], 'p_0': [0.1576923076923077, 0.3205128205128205, 0.5051282051282051, 0.5666666666666667, 0.6974358974358974, 0.4141025641025641, 0.7205128205128205, 0.6948717948717948, 0.982051282051282, 0.25875000000000004, 0.41500000000000004, 0.5900000000000001, 0.714375, 0.784375, 0.595, 0.821875, 0.884375, 1.0, 0.818125, 0.95125, 0.980625, 0.991875, 0.996875, 0.996875, 1.0, 1.0, 1.0, 0.99875, 0.999375, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3012820512820513, 0.47820512820512817, 0.5974358974358974, 0.7307692307692308, 0.8166666666666667, 0.5846153846153845, 0.8192307692307692, 0.7282051282051283, 0.9846153846153847, 0.5393749999999999, 0.733125, 0.828125, 0.894375, 0.9075, 0.8512500000000001, 0.93875, 0.97375, 1.0, 0.99625, 1.0, 0.999375, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.191025641025641, 0.3666666666666667, 0.458974358974359, 0.6025641025641026, 0.7320512820512821, 0.4294871794871795, 0.7346153846153847, 0.7192307692307692, 0.9871794871794872, 0.993125, 0.99875, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1448717948717949, 0.30641025641025643, 0.4948717948717949, 0.632051282051282, 0.6846153846153846, 0.4192307692307692, 0.7782051282051282, 0.717948717948718, 0.985897435897436], 'u': [0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0], 'v': [0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.5, 2.0, 10.0, 300.0]}

In [7]:
boot_data

     group  mean_fraction  mean_number  boot_var       p_0     u      v
0   [0, 0]       3.259598     1.793590  0.088831  0.157692   0.5    0.6
1   [0, 0]       2.449540     1.138462  0.082650  0.320513   0.6    0.7
2   [0, 0]       1.654431     0.664103  0.069271  0.505128   0.7    0.8
3   [0, 0]       1.579741     0.558974  0.076082  0.566667   0.8    0.9
4   [0, 0]       1.172968     0.370513  0.070141  0.697436   0.9    1.0
..     ...            ...          ...       ...       ...   ...    ...
85  [3, 3]       1.184865     0.374359  0.067928  0.684615   0.9    1.0
86  [3, 3]       3.549966     0.885897  0.130189  0.419231   1.0    1.5
87  [3, 3]       1.394132     0.244872  0.101441  0.778205   1.5    2.0
88  [3, 3]       4.016103     0.337179  0.284572  0.717949   2.0   10.0
89  [3, 3]       1.027513     0.014103  0.481344  0.985897  10.0  300.0

[90 rows x 7 columns]

In [8]:
model = CmdStanModel(stan_file="ture_ibd_popn4_bootstrap.stan")

15:24:36 - cmdstanpy - INFO - compiling stan file /Users/qichen/github/admix_stan/inference/ture_ibd_popn4_bootstrap.stan to exe file /Users/qichen/github/admix_stan/inference/ture_ibd_popn4_bootstrap
15:24:45 - cmdstanpy - INFO - compiled model executable: /Users/qichen/github/admix_stan/inference/ture_ibd_popn4_bootstrap

In [13]:
fit = model.variational(data = json_ibd, iter = 10000)

20:45:48 - cmdstanpy - INFO - Chain [1] start processing
20:45:49 - cmdstanpy - INFO - Chain [1] done processing

In [14]:
print(fit.variational_params_dict)

OrderedDict([('lp__', np.float64(0.0)), ('log_p__', np.float64(0.0)), ('log_g__', np.float64(0.0)), ('N[1]', np.float64(5622.2519)), ('N[2]', np.float64(7390.3845)), ('N[3]', np.float64(5095.5288)), ('N[4]', np.float64(16948.359)), ('T1', np.float64(26.713497)), ('fraction', np.float64(0.28767241))])

In [9]:
fit = model.sample(data=json_ibd, chains=4, iter_sampling=1000, iter_warmup=500, seed=123)

15:24:48 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/1500 [00:00<?, ?it/s, (Warmup)]


chain 1:   7%|▋         | 100/1500 [00:00<00:01, 962.92it/s, (Warmup)]


chain 1:  20%|██        | 300/1500 [00:00<00:01, 1162.57it/s, (Warmup)]


chain 1:  33%|███▎      | 500/1500 [00:00<00:00, 1342.54it/s, (Sampling)]





chain 1:  47%|████▋     | 700/1500 [00:00<00:00, 1451.62it/s, (Sampling)]


chain 1:  60%|██████    | 900/1500 [00:00<00:00, 1495.55it/s, (Sampling)]


chain 1:  73%|███████▎  | 1100/1500 [00:00<00:00, 1543.75it/s, (Sampling)]


chain 1:  87%|████████▋ | 1300/1500 [00:00<00:00, 1599.67it/s, (Sampling)]

chain 1: 100%|██████████| 1500/1500 [00:01<00:00, 1596.13it/s, (Sampling)]



chain 1: 100%|██████████| 1500/1500 [00:01<00:00, 1267.89it/s, (Sampling completed)]
chain 2: 100%|██████████| 1500/1500 [00:01<00:00, 1268.52it/s, (Sampling completed)]

chain 3: 100%|██████████| 1500/1500 [00:01<00:00, 1268.93it/s, (Sampling completed)]


chain 4: 100%|██████████| 1500/1500 [00:01<00:00, 1269.12it/s, (Sampling completed)]

15:24:49 - cmdstanpy - INFO - CmdStan done processing.

In [10]:
fit.summary()

,Mean,MCSE,StdDev,MAD,5%,50%,95%,ESS_bulk,ESS_tail,ESS_bulk/s,R_hat
lp__,-349.152000,0.041764,1.769390,1.586540,-352.580000,-348.797000,-346.951000,1779.66,2506.95,679.520,1.00128
N[1],10666.500000,3.474910,165.204000,164.848000,10397.900000,10664.500000,10935.600000,2258.10,2490.49,862.201,1.00175
N[2],9107.610000,9.644740,521.398000,511.818000,8317.700000,9077.810000,9997.040000,3011.77,1994.12,1149.970,1.00001
N[3],10694.300000,3.349880,176.194000,176.133000,10408.600000,10692.700000,10987.800000,2820.54,2940.15,1076.950,1.00034
N[4],9489.600000,8.523110,502.213000,497.287000,8721.180000,9465.350000,10326.800000,3606.15,2962.53,1376.920,1.00027
T1,67.585600,0.068333,3.453250,3.398590,61.972900,67.609200,73.278500,2581.78,2672.27,985.788,1.00028
fraction,0.633782,0.000188,0.008455,0.008336,0.620098,0.633748,0.647638,2032.42,2582.09,776.028,1.00088