In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import math
from cmdstanpy import CmdStanModel

/var/folders/x8/k3jsg9l14mg7njszvfns0ls00000gn/T/ipykernel_33571/1712715925.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
/Users/qichen/anaconda3/envs/msprime-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [21]:
# Prepare for the data
# true_N is [3000,3000,3000,3000,7000,7000], 7000s are given.
# true_T is [30,150,400], 150 and 400 are given.

ibd = pd.read_json('../ibd_admix_data.json')
ibd['index'] = ibd['index'].apply(tuple)
ibd['group'] = ibd['group'].apply(tuple)
grouped = ibd.groupby(['group','u','v'])
n_boot = 1000

columns = ['group','mean_fraction','mean_number','boot_var','p_0','u','v']
boot_data = pd.DataFrame(columns = columns)
for name, group in grouped:
    gg = name[0]
    u = name[1]
    v = name[2]
    non_zero = [i for i in group['fraction'] if i > 0]
    p_0 = 1- (len(non_zero)/len(group['fraction']))
    number_mean = group['number'].mean()
    sample_mean = group['fraction'].mean()
    bootstrap_means = []

    for _ in range(n_boot):
        sample = np.random.choice(group['fraction'], size=len(group['fraction']), replace=True)
        bootstrap_means.append(np.mean(sample))

# Estimate variance
    variance_estimate = np.var(bootstrap_means)
    new_row = [gg,sample_mean,number_mean,variance_estimate,p_0,u,v]
    boot_data.loc[len(boot_data)] = new_row

In [22]:
print(boot_data.head())

    group  mean_fraction  mean_number      boot_var       p_0     u     v
0  (0, 0)       0.000863     0.238462  3.928671e-09  0.788462  0.70  0.75
1  (0, 0)       0.000836     0.215385  4.937020e-09  0.821795  0.75  0.80
2  (0, 0)       0.000965     0.234615  4.758057e-09  0.788462  0.80  0.85
3  (0, 0)       0.000801     0.183333  4.309650e-09  0.834615  0.85  0.90
4  (0, 0)       0.000647     0.139744  4.283904e-09  0.875641  0.90  0.95

In [23]:
boot_data['mean_fraction'] = boot_data['mean_fraction'] * 1000
boot_data['boot_var'] = boot_data['boot_var'] * 1000000
boot_data['group'] = boot_data['group'].apply(list)
json_ibd = boot_data.to_dict(orient='list')
print(json_ibd)
json_ibd['N_obs'] = len(boot_data)
json_ibd['length'] = 200
json_ibd['outgroup_N'] = 14000
json_ibd['ancestral_T'] = 400
json_ibd['T2'] = 150
json_ibd['ancestral_N'] = 14000

{'group': [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'mean_fraction': [0.8628838461538424, 0.8355936538461526, 0.9654707051282027, 0.8014564743589732, 0.6466608974358936, 0.6667209615384615, 4.515166346153821, 2.5793445512820448, 1.5539038461538448, 0.8383654487179487, 0.5785852564102564, 0.5121641025641026, 0.43807442307692307, 0.4871026282051282, 0.33833839743589744, 0.3289886538461539, 0.37105717948717953, 0.37928198717948725, 0.5120965384615385, 0.5959341874999975, 0.5917058124999988, 0.45496078124999934, 0.30308203125, 0.2686548437499994, 0.2805265937499987, 1.4463722499999982, 0.6983379999999995, 0.3944035, 0.15032503125, 0.13083331250000002, 0.04730290624999999, 0.10834390624999998, 0.0, 0.0, 0.0181425, 0.0192095625, 0.0, 0.0, 0.34325346875, 0.37074056249999937, 0.26755134375, 0.25577465625, 0.17943003124999998, 0.15853915624999998, 0.6733443437499994, 0.10737531250000001, 0.01976725, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0674873125, 0.033673843749999995, 0.0052197499999999996, 0.01623284375, 0.0174835, 0.0060990624999999994, 0.0086045625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9948876923076885, 0.6301555769230769, 0.666556538461536, 0.39359692307692307, 0.5345086538461539, 0.4746419871794859, 3.55116846153845, 2.1006780769230753, 1.1209684615384614, 0.7129135897435899, 0.7277120512820512, 0.36098487179487176, 0.24881115384615385, 0.15099448717948719, 0.29946570512820514, 0.21676416666666665, 0.2048425, 0.3311977564102564, 0.40143282051282053, 0.8596737812499944, 0.7159322187499969, 0.67039346875, 0.6461045624999975, 0.5173019375, 0.4749328124999999, 3.488352031249983, 1.908175312499999, 1.0337747187499988, 0.69305959375, 0.4255289062499999, 0.39056162499999997, 0.27536978125, 0.17531978125, 0.11384265625000001, 0.07246865624999999, 0.03931734375, 0.140578, 0.05643878125, 0.05405709375, 0.053147, 0.015236843749999998, 0.0136995, 0.017575906250000002, 0.0, 0.01213409375, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.036007499999996, 0.996557371794868, 0.7642900641025642, 0.7173767948717936, 0.6233576923076922, 0.6127564743589744, 4.449838846153827, 2.7342397435897374, 1.951823653846151, 1.2318074358974358, 0.7014902564102564, 0.5164878846153845, 0.4618515384615385, 0.5756735256410257, 0.200320641025641, 0.3374441025641025, 0.21380506410256409, 0.34055839743589744, 0.3935183333333334, 0.0226259375, 0.01223053125, 0.015422125000000002, 0.019241968749999998, 0.00863846875, 0.0, 0.010711937500000001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.4610664102564, 1.4210846153846037, 1.2888566025640973, 1.032554871794868, 0.9100495512820475, 0.9456445512820513, 4.951278653846127, 2.5984405128205066, 1.4037193589743564, 1.2084933974358973, 0.7448834615384614, 0.3338501923076923, 0.3484957692307692, 0.30272115384615383, 0.26720051282051277, 0.2216270512820513, 0.4493530128205128, 0.28803108974358976, 0.40131346153846154], 'mean_number': [0.23846153846153847, 0.2153846153846154, 0.23461538461538461, 0.18333333333333332, 0.13974358974358975, 0.1371794871794872, 0.75, 0.3, 0.13846153846153847, 0.06153846153846154, 0.035897435897435895, 0.026923076923076925, 0.020512820512820513, 0.020512820512820513, 0.01282051282051282, 0.011538461538461539, 0.011538461538461539, 0.010256410256410256, 0.011538461538461539, 0.164375, 0.1525, 0.110625, 0.069375, 0.058125, 0.0575, 0.240625, 0.081875, 0.03625, 0.01125, 0.008125, 0.0025, 0.005, 0.0, 0.0, 0.000625, 0.000625, 0.0, 0.0, 0.095, 0.095625, 0.065, 0.05875, 0.03875, 0.0325, 0.11625, 0.013125, 0.001875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01875, 0.00875, 0.00125, 0.00375, 0.00375, 0.00125, 0.00125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2743589743589744, 0.16282051282051282, 0.16153846153846155, 0.08974358974358974, 0.11538461538461539, 0.09743589743589744, 0.5987179487179487, 0.24743589743589745, 0.10128205128205128, 0.052564102564102565, 0.04487179487179487, 0.019230769230769232, 0.011538461538461539, 0.00641025641025641, 0.011538461538461539, 0.007692307692307693, 0.00641025641025641, 0.008974358974358974, 0.008974358974358974, 0.2375, 0.185, 0.1625, 0.148125, 0.111875, 0.0975, 0.578125, 0.223125, 0.093125, 0.05125, 0.02625, 0.02125, 0.013125, 0.0075, 0.004375, 0.0025, 0.00125, 0.00375, 0.00125, 0.015, 0.01375, 0.00375, 0.003125, 0.00375, 0.0, 0.001875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2858974358974359, 0.25769230769230766, 0.1858974358974359, 0.1641025641025641, 0.1346153846153846, 0.12564102564102564, 0.7346153846153847, 0.31794871794871793, 0.17435897435897435, 0.08974358974358974, 0.04358974358974359, 0.028205128205128206, 0.021794871794871794, 0.02435897435897436, 0.007692307692307693, 0.011538461538461539, 0.00641025641025641, 0.008974358974358974, 0.008974358974358974, 0.00625, 0.003125, 0.00375, 0.004375, 0.001875, 0.0, 0.001875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.40512820512820513, 0.36666666666666664, 0.3128205128205128, 0.2358974358974359, 0.19743589743589743, 0.1935897435897436, 0.8256410256410256, 0.30256410256410254, 0.12564102564102564, 0.08974358974358974, 0.046153846153846156, 0.017948717948717947, 0.016666666666666666, 0.01282051282051282, 0.010256410256410256, 0.007692307692307693, 0.014102564102564103, 0.007692307692307693, 0.008974358974358974], 'boot_var': [0.003928671491336589, 0.0049370202654726025, 0.004758056941737835, 0.004309649521133084, 0.004283903624622155, 0.003872401453617803, 0.03541054126578823, 0.028403226203692292, 0.02211638371015593, 0.014175566539204215, 0.01171338798165861, 0.016075062662010697, 0.010701238746713857, 0.013856244147990141, 0.011351589399510384, 0.012199639654439367, 0.01597913415123444, 0.017466817129217573, 0.02984984356656412, 0.0013790621370665165, 0.001442127801195189, 0.0010794252088470412, 0.0007866605341957042, 0.0007869386409931378, 0.000824475459509135, 0.005887926830985816, 0.003741237045723007, 0.0031317932387347775, 0.0011751600000166216, 0.0015028591958204975, 0.0005628719314867892, 0.001431888198517406, 0.0, 0.0, 0.0003185964308303999, 0.00039543965273464566, 0.0, 0.0, 0.0007439209880436021, 0.0008935343121582363, 0.0006887099808067538, 0.000696371963624287, 0.0005273960074099462, 0.0004990416126759444, 0.0023093506374585837, 0.0005551549425316043, 0.00013442745600341402, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00015119138095249062, 8.580318146109004e-05, 1.4433450474161856e-05, 4.3526968428342316e-05, 5.0302106667903914e-05, 1.893805068008765e-05, 3.5283479476087795e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004392006848982711, 0.0033693446587760127, 0.0037283047576293746, 0.002083653084792096, 0.0027922731119549406, 0.00299680044034299, 0.02733589100288043, 0.025077767818623017, 0.015558721102822998, 0.012338535091343026, 0.016197344411839953, 0.008236818485254064, 0.0065730386563352975, 0.004518332772978772, 0.009039103806049734, 0.007708441306694727, 0.008789013118207062, 0.01581947390016697, 0.023378319226466784, 0.0019107132397871236, 0.0016834728809593377, 0.0017179414645045908, 0.0019021995374472324, 0.0014345190196739237, 0.0014065046933593184, 0.01341187153152123, 0.010146020686384089, 0.007050646200320678, 0.005177137017538543, 0.004398306506587254, 0.004400167610221018, 0.003112826683309047, 0.0026864608200113504, 0.001779834863216696, 0.0013606248054309647, 0.0007511372944823673, 0.003267413866684458, 0.0016215675554208347, 0.00013056315850542226, 0.00015077409400858898, 4.1803830206121846e-05, 3.794015857074301e-05, 5.236004125984699e-05, 0.0, 4.979711725868398e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004164737575298608, 0.004638453219135677, 0.0039530948740651274, 0.004460964395346823, 0.004094879987871955, 0.0037464192743555886, 0.03397043163402219, 0.026090228249368352, 0.030004884051334894, 0.021192327861181297, 0.01608821806242049, 0.010509059298460747, 0.011611165897778188, 0.016064837891214573, 0.006195199879537687, 0.012911919569259033, 0.008711704970817835, 0.02048360240220324, 0.022178182309339586, 4.689650987289981e-05, 3.172958784098208e-05, 3.6782260789940405e-05, 5.425141691390261e-05, 2.4785926487698322e-05, 0.0, 3.770568494034228e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.006334552979423054, 0.007287320623616742, 0.007235921821885959, 0.006227007244385985, 0.005266468142697679, 0.005654853068567776, 0.040604732289561074, 0.029769337329218135, 0.022416566704420375, 0.020579126306665703, 0.016192228961478913, 0.007660562714445888, 0.009915283207414843, 0.008772094436999401, 0.008630827448474258, 0.007668100669371244, 0.017160319414932762, 0.01414538914063377, 0.02137053801363452], 'p_0': [0.7884615384615384, 0.8217948717948718, 0.7884615384615384, 0.8346153846153846, 0.8756410256410256, 0.8692307692307693, 0.47435897435897434, 0.7384615384615385, 0.8692307692307693, 0.9397435897435897, 0.9641025641025641, 0.9756410256410256, 0.9794871794871794, 0.9794871794871794, 0.9871794871794872, 0.9884615384615385, 0.9884615384615385, 0.9897435897435898, 0.9884615384615385, 0.8512500000000001, 0.858125, 0.893125, 0.9325, 0.943125, 0.945, 0.785625, 0.92, 0.965, 0.98875, 0.9925, 0.9975, 0.995, 1.0, 1.0, 0.999375, 0.999375, 1.0, 1.0, 0.90875, 0.909375, 0.93875, 0.9425, 0.961875, 0.968125, 0.886875, 0.986875, 0.998125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.98125, 0.99125, 0.99875, 0.99625, 0.99625, 0.99875, 0.99875, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.7589743589743589, 0.8512820512820513, 0.8564102564102565, 0.9128205128205128, 0.8871794871794871, 0.9064102564102564, 0.5410256410256411, 0.7846153846153846, 0.9038461538461539, 0.95, 0.9576923076923077, 0.9807692307692307, 0.9884615384615385, 0.9935897435897436, 0.9884615384615385, 0.9923076923076923, 0.9935897435897436, 0.9910256410256411, 0.9910256410256411, 0.79, 0.8275, 0.85, 0.86625, 0.893125, 0.905, 0.5706249999999999, 0.7975, 0.91125, 0.94875, 0.97375, 0.97875, 0.986875, 0.9925, 0.995625, 0.9975, 0.99875, 0.99625, 0.99875, 0.985, 0.986875, 0.99625, 0.996875, 0.99625, 1.0, 0.998125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.7384615384615385, 0.7692307692307692, 0.823076923076923, 0.8576923076923078, 0.8782051282051282, 0.8846153846153846, 0.4833333333333333, 0.7102564102564102, 0.841025641025641, 0.9153846153846154, 0.9602564102564103, 0.9717948717948718, 0.9782051282051282, 0.9756410256410256, 0.9923076923076923, 0.9884615384615385, 0.9935897435897436, 0.9923076923076923, 0.9910256410256411, 0.99375, 0.996875, 0.99625, 0.995625, 0.998125, 1.0, 0.998125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.667948717948718, 0.6987179487179487, 0.7397435897435898, 0.7935897435897437, 0.8179487179487179, 0.8256410256410256, 0.43333333333333335, 0.735897435897436, 0.891025641025641, 0.9141025641025641, 0.9564102564102565, 0.982051282051282, 0.9833333333333333, 0.9871794871794872, 0.9897435897435898, 0.9923076923076923, 0.985897435897436, 0.9923076923076923, 0.9910256410256411], 'u': [0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0], 'v': [0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0]}

In [24]:
boot_data

      group  mean_fraction  mean_number  boot_var       p_0     u      v
0    [0, 0]       0.862884     0.238462  0.003929  0.788462  0.70   0.75
1    [0, 0]       0.835594     0.215385  0.004937  0.821795  0.75   0.80
2    [0, 0]       0.965471     0.234615  0.004758  0.788462  0.80   0.85
3    [0, 0]       0.801456     0.183333  0.004310  0.834615  0.85   0.90
4    [0, 0]       0.646661     0.139744  0.004284  0.875641  0.90   0.95
..      ...            ...          ...       ...       ...   ...    ...
185  [3, 3]       0.267201     0.010256  0.008631  0.989744  5.00   5.50
186  [3, 3]       0.221627     0.007692  0.007668  0.992308  5.50   6.00
187  [3, 3]       0.449353     0.014103  0.017160  0.985897  6.00   7.00
188  [3, 3]       0.288031     0.007692  0.014145  0.992308  7.00   8.00
189  [3, 3]       0.401313     0.008974  0.021371  0.991026  8.00  10.00

[190 rows x 7 columns]

In [6]:
model = CmdStanModel(stan_file="ture_ibd_popn4_bootstrap.stan")

16:10:25 - cmdstanpy - INFO - compiling stan file /Users/qichen/Desktop/admix_stan/inference/ture_ibd_popn4_bootstrap.stan to exe file /Users/qichen/Desktop/admix_stan/inference/ture_ibd_popn4_bootstrap
16:11:03 - cmdstanpy - INFO - compiled model executable: /Users/qichen/Desktop/admix_stan/inference/ture_ibd_popn4_bootstrap

In [25]:
fit = model.variational(data = json_ibd, iter = 10000)

16:21:35 - cmdstanpy - INFO - Chain [1] start processing
16:21:35 - cmdstanpy - INFO - Chain [1] done processing

In [26]:
print(fit.variational_params_dict)

OrderedDict({'lp__': 0.0, 'log_p__': 0.0, 'log_g__': 0.0, 'N[1]': 5352.1, 'N[2]': 9435.55, 'N[3]': 5591.07, 'N[4]': 15353.1, 'T1': 28.1171, 'fraction': 0.25458})

In [27]:
fit = model.sample(data=json_ibd, chains=4, iter_sampling=1000, iter_warmup=500, seed=123)

16:21:44 - cmdstanpy - INFO - CmdStan start processing

chain 1 |          | 00:00 Status


chain 1 |█▏        | 00:00 Iteration:    1 / 1500 [  0%]  (Warmup)


chain 1 |██▎       | 00:00 Iteration:  200 / 1500 [ 13%]  (Warmup)







































chain 1 |██▉       | 00:04 Iteration:  300 / 1500 [ 20%]  (Warmup)

chain 1 |██████████| 00:51 Sampling completed
chain 2 |██████████| 00:51 Sampling completed
chain 3 |██████████| 00:51 Sampling completed
chain 4 |██████████| 00:51 Sampling completed

16:22:36 - cmdstanpy - INFO - CmdStan done processing.
16:22:36 - cmdstanpy - WARNING - Some chains may have failed to converge.
	Chain 2 had 134 iterations at max treedepth (13.4%)
	Use the "diagnose()" method on the CmdStanMCMC object to see further information.

In [28]:
fit.summary()

,Mean,MCSE,StdDev,5%,50%,95%,N_Eff,N_Eff/s,R_hat
lp__,-58581.40000,9886.77000,37433.70000,-65298.90000,-51303.90000,-51301.40000,14.33560,0.147147,1.18183
N[1],5248.65000,49.55040,139.21100,5035.58000,5282.34000,5303.19000,7.89323,0.081019,1.36681
N[2],15071.60000,6708.08000,9604.38000,9307.09000,9690.00000,34036.70000,2.04994,0.021041,10.87760
N[3],6516.38000,1177.01000,5369.70000,5637.34000,5655.33000,6121.91000,20.81310,0.213635,1.11792
N[4],15297.70000,305.51200,707.62300,13295.20000,15535.00000,15566.90000,5.36472,0.055066,2.40599
T1,27.14307,1.46226,4.95841,26.84660,28.20220,28.34640,11.49835,0.118020,1.23744
fraction,0.25484,0.00304,0.00864,0.24321,0.25693,0.25798,8.07434,0.082880,1.36451