In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import math
from cmdstanpy import CmdStanModel

/opt/anaconda3/envs/stan_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
# Prepare for the data
# true_N is [3000,3000,3000,3000,7000,7000], 7000s are given.
# true_T is [30,150,400], 150 and 400 are given.

ibd = pd.read_json('../ibd_admix_data.json')
ibd['index'] = ibd['index'].apply(tuple)
ibd['group'] = ibd['group'].apply(tuple)
grouped = ibd.groupby(['group','u','v'])
n_boot = 1000

columns = ['group','mean_fraction','mean_number','boot_var','p_0','u','v']
boot_data = pd.DataFrame(columns = columns)
for name, group in grouped:
    gg = name[0]
    u = name[1]
    v = name[2]
    non_zero = [i for i in group['fraction'] if i > 0]
    p_0 = 1- (len(non_zero)/len(group['fraction']))
    number_mean = group['number'].mean()
    sample_mean = group['fraction'].mean()
    bootstrap_means = []

    for _ in range(n_boot):
        sample = np.random.choice(group['fraction'], size=len(group['fraction']), replace=True)
        bootstrap_means.append(np.mean(sample))

# Estimate variance
    variance_estimate = np.var(bootstrap_means)
    new_row = [gg,sample_mean,number_mean,variance_estimate,p_0,u,v]
    boot_data.loc[len(boot_data)] = new_row

In [8]:
print(boot_data.head())

    group  mean_fraction  mean_number      boot_var       p_0     u     v
0  (0, 0)       0.000863     0.238462  3.994999e-09  0.788462  0.70  0.75
1  (0, 0)       0.000836     0.215385  4.771345e-09  0.821795  0.75  0.80
2  (0, 0)       0.000965     0.234615  5.013184e-09  0.788462  0.80  0.85
3  (0, 0)       0.000801     0.183333  4.532120e-09  0.834615  0.85  0.90
4  (0, 0)       0.000647     0.139744  4.112496e-09  0.875641  0.90  0.95

In [10]:
boot_data['mean_fraction'] = boot_data['mean_fraction'] * 1000
boot_data['boot_var'] = np.sqrt(boot_data['boot_var']) * 1000
boot_data['group'] = boot_data['group'].apply(list)
json_ibd = boot_data.to_dict(orient='list')
print(json_ibd)
json_ibd['N_obs'] = len(boot_data)
json_ibd['length'] = 200
json_ibd['outgroup_N'] = 14000
json_ibd['ancestral_T'] = 400
json_ibd['T2'] = 150
json_ibd['ancestral_N'] = 14000

{'group': [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 2], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [0, 3], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'mean_fraction': [0.8628838461538424, 0.8355936538461526, 0.9654707051282027, 0.8014564743589732, 0.6466608974358936, 0.6667209615384615, 4.515166346153821, 2.5793445512820448, 1.5539038461538448, 0.8383654487179487, 0.5785852564102564, 0.5121641025641026, 0.43807442307692307, 0.4871026282051282, 0.33833839743589744, 0.3289886538461539, 0.37105717948717953, 0.37928198717948725, 0.5120965384615385, 0.5959341874999975, 0.5917058124999988, 0.45496078124999934, 0.30308203125, 0.2686548437499994, 0.2805265937499987, 1.4463722499999982, 0.6983379999999995, 0.3944035, 0.15032503125, 0.13083331250000002, 0.04730290624999999, 0.10834390624999998, 0.0, 0.0, 0.0181425, 0.0192095625, 0.0, 0.0, 0.34325346875, 0.37074056249999937, 0.26755134375, 0.25577465625, 0.17943003124999998, 0.15853915624999998, 0.6733443437499994, 0.10737531250000001, 0.01976725, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0674873125, 0.033673843749999995, 0.0052197499999999996, 0.01623284375, 0.0174835, 0.0060990624999999994, 0.0086045625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9948876923076885, 0.6301555769230769, 0.666556538461536, 0.39359692307692307, 0.5345086538461539, 0.4746419871794859, 3.55116846153845, 2.1006780769230753, 1.1209684615384614, 0.7129135897435899, 0.7277120512820512, 0.36098487179487176, 0.24881115384615385, 0.15099448717948719, 0.29946570512820514, 0.21676416666666665, 0.2048425, 0.3311977564102564, 0.40143282051282053, 0.8596737812499944, 0.7159322187499969, 0.67039346875, 0.6461045624999975, 0.5173019375, 0.4749328124999999, 3.488352031249983, 1.908175312499999, 1.0337747187499988, 0.69305959375, 0.4255289062499999, 0.39056162499999997, 0.27536978125, 0.17531978125, 0.11384265625000001, 0.07246865624999999, 0.03931734375, 0.140578, 0.05643878125, 0.05405709375, 0.053147, 0.015236843749999998, 0.0136995, 0.017575906250000002, 0.0, 0.01213409375, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.036007499999996, 0.996557371794868, 0.7642900641025642, 0.7173767948717936, 0.6233576923076922, 0.6127564743589744, 4.449838846153827, 2.7342397435897374, 1.951823653846151, 1.2318074358974358, 0.7014902564102564, 0.5164878846153845, 0.4618515384615385, 0.5756735256410257, 0.200320641025641, 0.3374441025641025, 0.21380506410256409, 0.34055839743589744, 0.3935183333333334, 0.0226259375, 0.01223053125, 0.015422125000000002, 0.019241968749999998, 0.00863846875, 0.0, 0.010711937500000001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.4610664102564, 1.4210846153846037, 1.2888566025640973, 1.032554871794868, 0.9100495512820475, 0.9456445512820513, 4.951278653846127, 2.5984405128205066, 1.4037193589743564, 1.2084933974358973, 0.7448834615384614, 0.3338501923076923, 0.3484957692307692, 0.30272115384615383, 0.26720051282051277, 0.2216270512820513, 0.4493530128205128, 0.28803108974358976, 0.40131346153846154], 'mean_number': [0.23846153846153847, 0.2153846153846154, 0.23461538461538461, 0.18333333333333332, 0.13974358974358975, 0.1371794871794872, 0.75, 0.3, 0.13846153846153847, 0.06153846153846154, 0.035897435897435895, 0.026923076923076925, 0.020512820512820513, 0.020512820512820513, 0.01282051282051282, 0.011538461538461539, 0.011538461538461539, 0.010256410256410256, 0.011538461538461539, 0.164375, 0.1525, 0.110625, 0.069375, 0.058125, 0.0575, 0.240625, 0.081875, 0.03625, 0.01125, 0.008125, 0.0025, 0.005, 0.0, 0.0, 0.000625, 0.000625, 0.0, 0.0, 0.095, 0.095625, 0.065, 0.05875, 0.03875, 0.0325, 0.11625, 0.013125, 0.001875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01875, 0.00875, 0.00125, 0.00375, 0.00375, 0.00125, 0.00125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2743589743589744, 0.16282051282051282, 0.16153846153846155, 0.08974358974358974, 0.11538461538461539, 0.09743589743589744, 0.5987179487179487, 0.24743589743589745, 0.10128205128205128, 0.052564102564102565, 0.04487179487179487, 0.019230769230769232, 0.011538461538461539, 0.00641025641025641, 0.011538461538461539, 0.007692307692307693, 0.00641025641025641, 0.008974358974358974, 0.008974358974358974, 0.2375, 0.185, 0.1625, 0.148125, 0.111875, 0.0975, 0.578125, 0.223125, 0.093125, 0.05125, 0.02625, 0.02125, 0.013125, 0.0075, 0.004375, 0.0025, 0.00125, 0.00375, 0.00125, 0.015, 0.01375, 0.00375, 0.003125, 0.00375, 0.0, 0.001875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2858974358974359, 0.25769230769230766, 0.1858974358974359, 0.1641025641025641, 0.1346153846153846, 0.12564102564102564, 0.7346153846153847, 0.31794871794871793, 0.17435897435897435, 0.08974358974358974, 0.04358974358974359, 0.028205128205128206, 0.021794871794871794, 0.02435897435897436, 0.007692307692307693, 0.011538461538461539, 0.00641025641025641, 0.008974358974358974, 0.008974358974358974, 0.00625, 0.003125, 0.00375, 0.004375, 0.001875, 0.0, 0.001875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.40512820512820513, 0.36666666666666664, 0.3128205128205128, 0.2358974358974359, 0.19743589743589743, 0.1935897435897436, 0.8256410256410256, 0.30256410256410254, 0.12564102564102564, 0.08974358974358974, 0.046153846153846156, 0.017948717948717947, 0.016666666666666666, 0.01282051282051282, 0.010256410256410256, 0.007692307692307693, 0.014102564102564103, 0.007692307692307693, 0.008974358974358974], 'boot_var': [0.0632060064966959, 0.06907492463207336, 0.07080384078522448, 0.06732102557614589, 0.06412874551232377, 0.06097526482924519, 0.1839384152257542, 0.17302931394063953, 0.1475970403261288, 0.1189049913720944, 0.11266513740837651, 0.12283212002174668, 0.10649965708095042, 0.12203535702512536, 0.10619278897968222, 0.10804793217994833, 0.12294077314286739, 0.1337579787509166, 0.17633040904787095, 0.03963045380970704, 0.03739732705328115, 0.03362118342478454, 0.0282024127538511, 0.027531543482349055, 0.02907927529578064, 0.07505332743690131, 0.06187523426321809, 0.0517104572136719, 0.03495987535455124, 0.03890493520042599, 0.023572126766098923, 0.03777812966942559, 0.0, 0.0, 0.018558411885243407, 0.019333553860396795, 0.0, 0.0, 0.027046256069279417, 0.03037004756523677, 0.026928130703445505, 0.027225648027774114, 0.02236183702785615, 0.022281606262147906, 0.04829462177324891, 0.023671321602357385, 0.011320966648442954, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012085011092813491, 0.00913475858932691, 0.003685749710053912, 0.006563254139930731, 0.007145001437600635, 0.004208174714682003, 0.005830814208073017, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0666189120783211, 0.05508076808130782, 0.061520164842719056, 0.0487895487719759, 0.054050273596737655, 0.05215344881144521, 0.1677982367299461, 0.1503915741888382, 0.1291825103038474, 0.11442711901782346, 0.1303885233095224, 0.09346396920019344, 0.08094894770852794, 0.06763144333815325, 0.09837375312969837, 0.08739652467875128, 0.09105217532303009, 0.12099122946059114, 0.147131924076228, 0.045311875120989324, 0.041562858049244616, 0.04361702650265132, 0.043013475866240845, 0.03810309344216884, 0.0387422866936494, 0.11536758326367866, 0.10029711028594547, 0.08471263079500295, 0.07308197052121274, 0.06630066735060407, 0.06640057064315165, 0.060210993139352596, 0.05312636642817871, 0.043772362975918286, 0.03527880744400079, 0.02782795280147699, 0.05679733273338404, 0.04088438013785443, 0.010801481616490556, 0.011384719550111689, 0.006199032506296442, 0.006153574136942009, 0.007226038239214346, 0.0, 0.00714972916960535, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0651921768904531, 0.06950189084283857, 0.05978202397748549, 0.06738077647808598, 0.06527478638892693, 0.06407663342383924, 0.19436113574737435, 0.16726050640030865, 0.1677957307220109, 0.15218565243541599, 0.13249635283681022, 0.10742113996622873, 0.11532062461065479, 0.13116479782439633, 0.08003747469673803, 0.11305064056741476, 0.09912947146841695, 0.14496295469949902, 0.14729743656745373, 0.007084925333894872, 0.00571793486579144, 0.006107333599283133, 0.007509406476154033, 0.005093435135837837, 0.0, 0.006035079069621918, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08102603504373464, 0.0870225784900231, 0.0832557839991222, 0.07811602261310814, 0.07420140515387962, 0.07598488341893003, 0.19794627951908228, 0.16323053740657062, 0.150449675658054, 0.14407447251864794, 0.12655190205072697, 0.08784937671559484, 0.0971292174437855, 0.09630944821461171, 0.09405763725975157, 0.09006740585821016, 0.13215624130812018, 0.1194692304364881, 0.15960521787780638], 'p_0': [0.7884615384615384, 0.8217948717948718, 0.7884615384615384, 0.8346153846153846, 0.8756410256410256, 0.8692307692307693, 0.47435897435897434, 0.7384615384615385, 0.8692307692307693, 0.9397435897435897, 0.9641025641025641, 0.9756410256410256, 0.9794871794871794, 0.9794871794871794, 0.9871794871794872, 0.9884615384615385, 0.9884615384615385, 0.9897435897435898, 0.9884615384615385, 0.8512500000000001, 0.858125, 0.893125, 0.9325, 0.943125, 0.945, 0.785625, 0.92, 0.965, 0.98875, 0.9925, 0.9975, 0.995, 1.0, 1.0, 0.999375, 0.999375, 1.0, 1.0, 0.90875, 0.909375, 0.93875, 0.9425, 0.961875, 0.968125, 0.886875, 0.986875, 0.998125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.98125, 0.99125, 0.99875, 0.99625, 0.99625, 0.99875, 0.99875, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.7589743589743589, 0.8512820512820513, 0.8564102564102565, 0.9128205128205128, 0.8871794871794871, 0.9064102564102564, 0.5410256410256411, 0.7846153846153846, 0.9038461538461539, 0.95, 0.9576923076923077, 0.9807692307692307, 0.9884615384615385, 0.9935897435897436, 0.9884615384615385, 0.9923076923076923, 0.9935897435897436, 0.9910256410256411, 0.9910256410256411, 0.79, 0.8275, 0.85, 0.86625, 0.893125, 0.905, 0.5706249999999999, 0.7975, 0.91125, 0.94875, 0.97375, 0.97875, 0.986875, 0.9925, 0.995625, 0.9975, 0.99875, 0.99625, 0.99875, 0.985, 0.986875, 0.99625, 0.996875, 0.99625, 1.0, 0.998125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.7384615384615385, 0.7692307692307692, 0.823076923076923, 0.8576923076923078, 0.8782051282051282, 0.8846153846153846, 0.4833333333333333, 0.7102564102564102, 0.841025641025641, 0.9153846153846154, 0.9602564102564103, 0.9717948717948718, 0.9782051282051282, 0.9756410256410256, 0.9923076923076923, 0.9884615384615385, 0.9935897435897436, 0.9923076923076923, 0.9910256410256411, 0.99375, 0.996875, 0.99625, 0.995625, 0.998125, 1.0, 0.998125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.667948717948718, 0.6987179487179487, 0.7397435897435898, 0.7935897435897437, 0.8179487179487179, 0.8256410256410256, 0.43333333333333335, 0.735897435897436, 0.891025641025641, 0.9141025641025641, 0.9564102564102565, 0.982051282051282, 0.9833333333333333, 0.9871794871794872, 0.9897435897435898, 0.9923076923076923, 0.985897435897436, 0.9923076923076923, 0.9910256410256411], 'u': [0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 0.7000000000000001, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0], 'v': [0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0, 0.75, 0.8, 0.85, 0.9, 0.9500000000000001, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 7.0, 8.0, 10.0]}

In [11]:
boot_data

      group  mean_fraction  mean_number  boot_var       p_0     u      v
0    [0, 0]       0.862884     0.238462  0.063206  0.788462  0.70   0.75
1    [0, 0]       0.835594     0.215385  0.069075  0.821795  0.75   0.80
2    [0, 0]       0.965471     0.234615  0.070804  0.788462  0.80   0.85
3    [0, 0]       0.801456     0.183333  0.067321  0.834615  0.85   0.90
4    [0, 0]       0.646661     0.139744  0.064129  0.875641  0.90   0.95
..      ...            ...          ...       ...       ...   ...    ...
185  [3, 3]       0.267201     0.010256  0.094058  0.989744  5.00   5.50
186  [3, 3]       0.221627     0.007692  0.090067  0.992308  5.50   6.00
187  [3, 3]       0.449353     0.014103  0.132156  0.985897  6.00   7.00
188  [3, 3]       0.288031     0.007692  0.119469  0.992308  7.00   8.00
189  [3, 3]       0.401313     0.008974  0.159605  0.991026  8.00  10.00

[190 rows x 7 columns]

In [12]:
model = CmdStanModel(stan_file="ture_ibd_popn4_bootstrap.stan")

20:45:40 - cmdstanpy - INFO - compiling stan file /Users/qi/Documents/GitHub/admix_stan/inference/ture_ibd_popn4_bootstrap.stan to exe file /Users/qi/Documents/GitHub/admix_stan/inference/ture_ibd_popn4_bootstrap
20:45:46 - cmdstanpy - INFO - compiled model executable: /Users/qi/Documents/GitHub/admix_stan/inference/ture_ibd_popn4_bootstrap

In [13]:
fit = model.variational(data = json_ibd, iter = 10000)

20:45:48 - cmdstanpy - INFO - Chain [1] start processing
20:45:49 - cmdstanpy - INFO - Chain [1] done processing

In [14]:
print(fit.variational_params_dict)

OrderedDict([('lp__', np.float64(0.0)), ('log_p__', np.float64(0.0)), ('log_g__', np.float64(0.0)), ('N[1]', np.float64(5622.2519)), ('N[2]', np.float64(7390.3845)), ('N[3]', np.float64(5095.5288)), ('N[4]', np.float64(16948.359)), ('T1', np.float64(26.713497)), ('fraction', np.float64(0.28767241))])

In [15]:
fit = model.sample(data=json_ibd, chains=4, iter_sampling=1000, iter_warmup=500, seed=123)

20:46:02 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/1500 [00:00<?, ?it/s, (Warmup)]



chain 1:   7%|▋         | 100/1500 [00:00<00:02, 529.81it/s, (Warmup)]


chain 1:  20%|██        | 300/1500 [00:00<00:01, 860.75it/s, (Warmup)]



chain 1:  33%|███▎      | 500/1500 [00:00<00:00, 1062.70it/s, (Sampling)]






chain 1:  47%|████▋     | 700/1500 [00:00<00:00, 1172.68it/s, (Sampling)]


chain 1:  60%|██████    | 900/1500 [00:00<00:00, 1239.02it/s, (Sampling)]


chain 1:  73%|███████▎  | 1100/1500 [00:00<00:00, 1304.65it/s, (Sampling)]


chain 1:  87%|████████▋ | 1300/1500 [00:01<00:00, 1310.55it/s, (Sampling)]


chain 1: 100%|██████████| 1500/1500 [00:01<00:00, 1204.79it/s, (Sampling completed)]
chain 2: 100%|██████████| 1500/1500 [00:01<00:00, 1204.91it/s, (Sampling completed)]

chain 3: 100%|██████████| 1500/1500 [00:01<00:00, 1205.43it/s, (Sampling completed)]


chain 4: 100%|██████████| 1500/1500 [00:01<00:00, 1205.62it/s, (Sampling completed)]

20:46:03 - cmdstanpy - INFO - CmdStan done processing.

In [16]:
fit.summary()

,Mean,MCSE,StdDev,MAD,5%,50%,95%,ESS_bulk,ESS_tail,ESS_bulk/s,R_hat
lp__,-5.374250,0.043044,1.778890,1.641880,-8.74061,-5.035050,-3.158840,1823.51,2265.45,631.191,1.002260
N[1],5710.330000,2.375710,134.778000,135.091000,5490.87000,5707.340000,5933.580000,3239.53,2816.95,1121.330,1.000550
N[2],8140.590000,29.667300,1703.310000,1491.700000,5952.33000,7854.470000,11264.800000,4310.12,2712.17,1491.910,1.001520
N[3],5147.600000,1.939940,115.926000,114.845000,4964.96000,5143.300000,5345.530000,3586.14,3246.43,1241.310,1.001350
N[4],16695.900000,9.959380,635.056000,637.139000,15707.60000,16679.200000,17763.200000,4127.53,2883.52,1428.710,1.000390
T1,27.459500,0.028627,1.892740,1.877490,24.37310,27.412900,30.541000,4383.21,2584.92,1517.210,0.999721
fraction,0.286442,0.000170,0.009291,0.009236,0.27098,0.286306,0.302035,2983.10,2650.55,1032.570,1.000920